### ISSUE TITLE
React component got lost from the attached html node when ui-router changed state

### ISSUE THREAD

**Issue by Simon-Li** [nateabele/ui-router#17]
At the first time of ui-router runs up the default ui-view, the React component is working fine, but after state changed, the React component just lost from the dom. Any clues are greatly appreciated!

**Comment by nateabele** [comment]
Hi there. :smile: This is my personal (experimental) fork and is not officially supported. I think you're looking for [angular-ui/ui-router](https://github.com/angular-ui/ui-router), however, this sounds like a support question best suited for StackOverflow.
